import "@/assets/css/style.css";
import "@/assets/css/plugins/bootstrap-grid.css";
import "@/assets/css/plugins/font-awesome.min.css";
import "@/assets/css/plugins/swiper.min.css";
import "@/assets/css/plugins/fancybox.min.css";
import "@/assets/css/style.css";
import type { Metadata } from "next";
import ScrollTo from "./_scrollTo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Rueda de Negocios - ExpoSur 2024</title>
      </head>
      <body>
        <ScrollTo>{children}</ScrollTo>
      </body>
    </html>
  );
}
