import "@/assets/css/style.css";
import "@/assets/css/plugins/bootstrap-grid.css";
import "@/assets/css/plugins/font-awesome.min.css";
import "@/assets/css/plugins/swiper.min.css";
import "@/assets/css/plugins/fancybox.min.css";
import "@/assets/css/style.css";
import type { Metadata } from "next";
import Script from "next/script";
import Header from "@/components/layout/header/header";
import Menu from "@/components/layout/menu/menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* wrapper */}
      <div className="mil-wrapper" id="top">
        {/* cursor */}
        {/*   <div className="mil-ball">
          <span className="mil-icon-1">
            <svg viewBox="0 0 128 128">
              <path d="M106.1,41.9c-1.2-1.2-3.1-1.2-4.2,0c-1.2,1.2-1.2,3.1,0,4.2L116.8,61H11.2l14.9-14.9c1.2-1.2,1.2-3.1,0-4.2	c-1.2-1.2-3.1-1.2-4.2,0l-20,20c-1.2,1.2-1.2,3.1,0,4.2l20,20c0.6,0.6,1.4,0.9,2.1,0.9s1.5-0.3,2.1-0.9c1.2-1.2,1.2-3.1,0-4.2	L11.2,67h105.5l-14.9,14.9c-1.2,1.2-1.2,3.1,0,4.2c0.6,0.6,1.4,0.9,2.1,0.9s1.5-0.3,2.1-0.9l20-20c1.2-1.2,1.2-3.1,0-4.2L106.1,41.9	z" />
            </svg>
          </span>
          <div className="mil-more-text">More</div>
          <div className="mil-choose-text">Сhoose</div>
        </div> */}
        {/* cursor end */}
        {/* preloader */}
        {/* <div class="mil-preloader">
        <div class="mil-preloader-animation">
            <div class="mil-pos-abs mil-animation-1">
                <p class="mil-h3 mil-muted mil-thin">Pioneering</p>
                <p class="mil-h3 mil-muted">Creative</p>
                <p class="mil-h3 mil-muted mil-thin">Excellence</p>
            </div>
            <div class="mil-pos-abs mil-animation-2">
                <div class="mil-reveal-frame">
                    <p class="mil-reveal-box"></p>
                    <p class="mil-h3 mil-muted mil-thin">ashley.com</p>
                </div>
            </div>
        </div>
    </div> */}
        {/* preloader end */}
        {/* scrollbar progress */}
        <div className="mil-progress-track">
          <div className="mil-progress" />
        </div>
        {/* scrollbar progress end */}
        {/* menu */}

        <Menu />

        {/* menu */}
        {/* curtain */}
        <div className="mil-curtain" />
        {/* curtain end */}
        {/* frame */}
        <Header />
        {/* frame end */}
        {/* content */}
        <div className="mil-content">
          <div id="swupMain" className="mil-main-transition">
            {children}
          </div>
        </div>
        {/* content */}
      </div>
      {/* wrapper end */}

      <Script src="js/plugins/jquery.min.js" />
      <Script src="js/plugins/swup.min.js" />
      <Script src="js/plugins/swiper.min.js" />
      <Script src="js/plugins/fancybox.min.js" />
      <Script src="js/plugins/gsap.min.js" />
      <Script src="js/plugins/smooth-scroll.js" />
      <Script src="js/plugins/ScrollTrigger.min.js" />
      <Script src="js/plugins/ScrollTo.min.js" />
      <Script src="js/main.js" />
    </>
  );
}
